# compose.sofolaPGv.yml

# Use postgres/example user/password credentials
# version: '3.1'

services:
  db:
    image: pgvector/pgvector:0.7.3-pg16
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # ignored except on the first run
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # ignored except on the first run
      POSTGRES_DB: PGv  # ignored except on the first run
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # PGDATA: /var/lib/postgresql/data/some_name/
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      # Persist data even if container is destroyed
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  # {in-host (external)}:{in-container (internal)}

volumes:
  pg_data: