# compose.sofolaPGv.yml

# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: ankane/pgvector
    # restart: always
    environment:
      POSTGRES_USER: oori
      POSTGRES_PASSWORD: example
      POSTGRES_DB: PGv
    ports:
      - 5432:5432  # {in-host (external)}:{in-container (internal)}
    volumes:
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  # {in-host (external)}:{in-container (internal)}